import { SignalItem } from "../types";

export const SIGNAL_REGISTRY: SignalItem[] = [
  {
    id: "ndvi_crop_type",
    name: "NDVI Crop-Type Mapping",
    source: "Sentinel-2 MSI",
    family: "crop",
    status: "provider-backed",
    resolution: "10 m",
    revisit: "5 days",
    description: "Multispectral optical reflectance signatures separating grain, legume, and cash crop signatures in peak vegetative growth.",
    agronomicUse: "Distinguishes commercial maize, small grains (sorghum, pearl millet), and tobacco fields for area estimation.",
  },
  {
    id: "sar_crop_type",
    name: "SAR Crop-Type Mapping",
    source: "Sentinel-1 C-band SAR",
    family: "crop",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "6–12 days",
    description: "Cloud-penetrating synthetic aperture radar backscatter (VV/VH dual-pol) capturing crop canopy structure and roughness.",
    agronomicUse: "Essential during rainy season cloud cover in Natural Region II & III when optical Sentinel-2 is obscured.",
  },
  {
    id: "landsat_sentinel_phenology",
    name: "Landsat–Sentinel Harmonized Phenology",
    source: "Landsat 8/9 + Sentinel-2",
    family: "phenology",
    status: "provider-backed",
    resolution: "30 m (HLS)",
    revisit: "2–3 days",
    description: "Harmonized Landsat-Sentinel (HLS) surface reflectance tracking emergence, greenup peak, and senescence curve.",
    agronomicUse: "Detects planting date shifts, dry spell stagnation, and physiological maturity for harvest timing.",
  },
  {
    id: "ndvi_phenology",
    name: "NDVI Phenology Trajectory Analysis",
    source: "Sentinel-2 / Landsat",
    family: "phenology",
    status: "provider-backed",
    resolution: "10–30 m",
    revisit: "5 days",
    description: "Normalized difference vegetation index temporal integrals calculating cumulative vegetative vigor.",
    agronomicUse: "Corroborates farmer self-reported yield against biomass accumulation curve.",
  },
  {
    id: "irrigated_rainfed",
    name: "Irrigated vs Rainfed Cropland Delineation",
    source: "Sentinel-2 + CHIRPS / NASA POWER",
    family: "water",
    status: "calibration-required",
    resolution: "10 m",
    revisit: "Decadal",
    description: "Cross-correlates dry-season greenness anomalies with precipitation deficit to flag actively irrigated schemes.",
    agronomicUse: "Identifies center-pivot winter wheat and dry-spell borehole supplemented plots vs rainfed maize.",
  },
  {
    id: "vegetation_irrigation_index",
    name: "Vegetation Irrigation Water Index (VIWI)",
    source: "Sentinel-2 + Weather Reanalysis",
    family: "water",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "5 days",
    description: "Shortwave infrared (SWIR) to near-infrared (NIR) spectral ratios measuring canopy cellular water volume.",
    agronomicUse: "Differentiates well-watered commercial pivots from water-stressed communal rainfed fields.",
  },
  {
    id: "vegetation_moisture",
    name: "Vegetation Moisture Content (NDWI / NDII)",
    source: "Sentinel-2 (B8A & B11/B12)",
    family: "water",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "5 days",
    description: "Normalized Difference Water Index capturing canopy leaf water content and turgidity.",
    agronomicUse: "Immediate indicator of mid-season moisture stress prior to visible thermal wilting.",
  },
  {
    id: "crop_water_stress",
    name: "Crop Water-Stress Index (CWSI)",
    source: "Sentinel-2 + Thermal & Reanalysis",
    family: "water",
    status: "calibration-required",
    resolution: "100 m",
    revisit: "Daily (modeled)",
    description: "Energy balance proxy comparing actual to potential evapotranspiration across cropped areas.",
    agronomicUse: "Critical early warning for El Niño mid-season dry spells in Natural Regions IV and V.",
  },
  {
    id: "modis_cropland_area",
    name: "MODIS National Cropland-Area Monitor",
    source: "Terra / Aqua MODIS",
    family: "land-cover",
    status: "provider-backed",
    resolution: "250 m",
    revisit: "Daily",
    description: "Coarse daily temporal resolution tracking national and provincial cropping footprint trends.",
    agronomicUse: "Macro-level district cultivated area validation for Ministry of Lands & Agriculture statistics.",
  },
  {
    id: "ndvi_savgol",
    name: "Savitzky–Golay NDVI Filtering",
    source: "Sentinel-2 / Landsat Pipeline",
    family: "phenology",
    status: "implemented",
    resolution: "10 m",
    revisit: "5 days",
    description: "Algorithmic temporal polynomial filtering eliminating atmospheric noise and cloud edge shadows.",
    agronomicUse: "Produces smooth, mathematically robust growth curves for automated anomaly detection.",
  },
  {
    id: "growing_season",
    name: "Growing-Season Dynamic Window Monitor",
    source: "Sentinel-2 / Landsat + Weather",
    family: "phenology",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "Weekly",
    description: "Detects Start of Season (SOS), Length of Season (LOS), and End of Season (EOS) milestones.",
    agronomicUse: "Confirms whether farmers met the optimum planting window or planted late under false rains.",
  },
  {
    id: "lai",
    name: "Leaf Area Index (LAI) Canopy Radiative Transfer",
    source: "Sentinel-2 Biophysical Processor",
    family: "biomass",
    status: "calibration-required",
    resolution: "10 m",
    revisit: "5 days",
    description: "One-sided green leaf area per unit ground surface area estimated through PROSAIL model inversion.",
    agronomicUse: "Provides physical biomass scaling factor to check against reported grain yield (harvest index).",
  },
  {
    id: "sentinel1_soil_moisture",
    name: "Sentinel-1 Radar Soil-Moisture Proxy",
    source: "Sentinel-1 SAR C-band",
    family: "soil",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "6–12 days",
    description: "Dielectric constant sensitivity in upper 0–5 cm topsoil calibrated against soil roughness.",
    agronomicUse: "Monitors seedbed moisture readiness before planting decisions in early November/December.",
  },
  {
    id: "sentinel2_soil_moisture",
    name: "Sentinel-2 Optical/SWIR Soil Drought Index",
    source: "Sentinel-2 MSI",
    family: "soil",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "5 days",
    description: "Shortwave infrared soil absorption variations over bare and sparsely vegetated ground.",
    agronomicUse: "Pinpoints localized soil dryness before crops reach permanent wilting point.",
  },
  {
    id: "landsat_soil_moisture",
    name: "Landsat Thermal Infrared Soil Water Proxy",
    source: "Landsat 8/9 TIRS",
    family: "soil",
    status: "calibration-required",
    resolution: "30 m (resampled)",
    revisit: "8–16 days",
    description: "Apparent Thermal Inertia (ATI) and Land Surface Temperature (LST) mapping ground water deficit.",
    agronomicUse: "Long-term soil moisture depletion trends across irrigation command areas.",
  },
];
