import { SignalItem } from "../types";

export const SIGNAL_REGISTRY: SignalItem[] = [
  {
    id: "ndvi_crop_type",
    name: "NDVI Crop-Type Mapping",
    source: "Sentinel-2 MSI",
    family: "crop",
    status: "provider-backed",
    resolution: "10 m",
    revisit: "5 days",
    description: "Multispectral optical reflectance signatures separating grain, legume, and cash crop signatures in peak vegetative growth.",
    agronomicUse: "Distinguishes commercial maize, small grains (sorghum, pearl millet), and tobacco fields for area estimation.",
    currentValue: "0.68",
    baselineValue: "0.62",
    anomaly: "+9.7%",
    anomalyPositive: true,
    unit: "NDVI (-1 to 1)",
    sparklineData: [0.22, 0.28, 0.35, 0.44, 0.52, 0.59, 0.65, 0.68, 0.67, 0.68],
  },
  {
    id: "sar_crop_type",
    name: "SAR Crop-Type Mapping",
    source: "Sentinel-1 C-band SAR",
    family: "crop",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "6–12 days",
    description: "Cloud-penetrating synthetic aperture radar backscatter (VV/VH dual-pol) capturing crop canopy structure and roughness.",
    agronomicUse: "Essential during rainy season cloud cover in Natural Region II & III when optical Sentinel-2 is obscured.",
    currentValue: "-13.4 dB",
    baselineValue: "-14.1 dB",
    anomaly: "+0.7 dB",
    anomalyPositive: true,
    unit: "VV/VH Backscatter",
    sparklineData: [-18.2, -17.5, -16.8, -15.9, -15.1, -14.4, -13.9, -13.6, -13.4, -13.4],
  },
  {
    id: "landsat_sentinel_phenology",
    name: "Landsat–Sentinel Harmonized Phenology",
    source: "Landsat 8/9 + Sentinel-2",
    family: "phenology",
    status: "provider-backed",
    resolution: "30 m (HLS)",
    revisit: "2–3 days",
    description: "Harmonized Landsat-Sentinel (HLS) surface reflectance tracking emergence, greenup peak, and senescence curve.",
    agronomicUse: "Detects planting date shifts, dry spell stagnation, and physiological maturity for harvest timing.",
    currentValue: "Peak Silking",
    baselineValue: "Day 78",
    anomaly: "+4 Days",
    anomalyPositive: true,
    unit: "Thermal Cum. (GDD)",
    sparklineData: [110, 240, 420, 650, 910, 1140, 1320, 1490, 1610, 1720],
  },
  {
    id: "ndvi_phenology",
    name: "NDVI Phenology Trajectory Analysis",
    source: "Sentinel-2 / Landsat",
    family: "phenology",
    status: "provider-backed",
    resolution: "10–30 m",
    revisit: "5 days",
    description: "Normalized difference vegetation index temporal integrals calculating cumulative vegetative vigor.",
    agronomicUse: "Corroborates farmer self-reported yield against biomass accumulation curve.",
    currentValue: "18.4",
    baselineValue: "16.9",
    anomaly: "+8.9%",
    anomalyPositive: true,
    unit: "Seasonal Integral",
    sparklineData: [2.1, 4.3, 7.1, 9.8, 12.4, 14.5, 16.2, 17.5, 18.1, 18.4],
  },
  {
    id: "irrigated_rainfed",
    name: "Irrigated vs Rainfed Cropland Delineation",
    source: "Sentinel-2 + CHIRPS / NASA POWER",
    family: "water",
    status: "calibration-required",
    resolution: "10 m",
    revisit: "Decadal",
    description: "Cross-correlates dry-season greenness anomalies with precipitation deficit to flag actively irrigated schemes.",
    agronomicUse: "Identifies center-pivot winter wheat and dry-spell borehole supplemented plots vs rainfed maize.",
    currentValue: "28.4% Irrigated",
    baselineValue: "26.1%",
    anomaly: "+2.3% Pct",
    anomalyPositive: true,
    unit: "Share of Scheme",
    sparklineData: [24.1, 24.5, 25.0, 25.8, 26.2, 26.9, 27.5, 27.9, 28.2, 28.4],
  },
  {
    id: "vegetation_irrigation_index",
    name: "Vegetation Irrigation Water Index (VIWI)",
    source: "Sentinel-2 + Weather Reanalysis",
    family: "water",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "5 days",
    description: "Shortwave infrared (SWIR) to near-infrared (NIR) spectral ratios measuring canopy cellular water volume.",
    agronomicUse: "Differentiates well-watered commercial pivots from water-stressed communal rainfed fields.",
    currentValue: "0.54",
    baselineValue: "0.49",
    anomaly: "+10.2%",
    anomalyPositive: true,
    unit: "Canopy Index",
    sparklineData: [0.38, 0.40, 0.42, 0.45, 0.48, 0.51, 0.53, 0.52, 0.53, 0.54],
  },
  {
    id: "vegetation_moisture",
    name: "Vegetation Moisture Content (NDWI / NDII)",
    source: "Sentinel-2 (B8A & B11/B12)",
    family: "water",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "5 days",
    description: "Normalized Difference Water Index capturing canopy leaf water content and turgidity.",
    agronomicUse: "Immediate indicator of mid-season moisture stress prior to visible thermal wilting.",
    currentValue: "0.31",
    baselineValue: "0.33",
    anomaly: "-6.1%",
    anomalyPositive: false,
    unit: "NDWI Index",
    sparklineData: [0.42, 0.41, 0.39, 0.38, 0.36, 0.34, 0.33, 0.32, 0.30, 0.31],
  },
  {
    id: "crop_water_stress",
    name: "Crop Water-Stress Index (CWSI)",
    source: "Sentinel-2 + Thermal & Reanalysis",
    family: "water",
    status: "calibration-required",
    resolution: "100 m",
    revisit: "Daily (modeled)",
    description: "Energy balance proxy comparing actual to potential evapotranspiration across cropped areas.",
    agronomicUse: "Critical early warning for El Niño mid-season dry spells in Natural Regions IV and V.",
    currentValue: "0.24 (Low)",
    baselineValue: "0.38 (High)",
    anomaly: "-36.8%",
    anomalyPositive: true,
    unit: "Stress Index (0-1)",
    sparklineData: [0.48, 0.45, 0.41, 0.38, 0.34, 0.31, 0.28, 0.26, 0.25, 0.24],
  },
  {
    id: "modis_cropland_area",
    name: "MODIS National Cropland-Area Monitor",
    source: "Terra / Aqua MODIS",
    family: "land-cover",
    status: "provider-backed",
    resolution: "250 m",
    revisit: "Daily",
    description: "Coarse daily temporal resolution tracking national and provincial cropping footprint trends.",
    agronomicUse: "Macro-level district cultivated area validation for Ministry of Agriculture, Mechanisation and Water Resources Development statistics.",
    currentValue: "1.42M Ha",
    baselineValue: "1.38M Ha",
    anomaly: "+2.9%",
    anomalyPositive: true,
    unit: "National Area (Ha)",
    sparklineData: [1.28, 1.30, 1.32, 1.34, 1.37, 1.39, 1.40, 1.41, 1.41, 1.42],
  },
  {
    id: "ndvi_savgol",
    name: "Savitzky–Golay NDVI Filtering",
    source: "Sentinel-2 / Landsat Pipeline",
    family: "phenology",
    status: "implemented",
    resolution: "10 m",
    revisit: "5 days",
    description: "Algorithmic temporal polynomial filtering eliminating atmospheric noise and cloud edge shadows.",
    agronomicUse: "Produces smooth, mathematically robust growth curves for automated anomaly detection.",
    currentValue: "0.71 Fit",
    baselineValue: "R² 0.94",
    anomaly: "Clean Signal",
    anomalyPositive: true,
    unit: "Smoothed NDVI",
    sparklineData: [0.20, 0.26, 0.33, 0.42, 0.51, 0.60, 0.66, 0.70, 0.71, 0.71],
  },
  {
    id: "growing_season",
    name: "Growing-Season Dynamic Window Monitor",
    source: "Sentinel-2 / Landsat + Weather",
    family: "phenology",
    status: "provider-backed",
    resolution: "20 m",
    revisit: "Weekly",
    description: "Detects Start of Season (SOS), Length of Season (LOS), and End of Season (EOS) milestones.",
    agronomicUse: "Confirms whether farmers met the optimum planting window or planted late under false rains.",
    currentValue: "Day 84 (Peak)",
    baselineValue: "125 Days",
    anomaly: "Normal Window",
    anomalyPositive: true,
    unit: "Season Progression",
    sparklineData: [10, 20, 32, 45, 58, 68, 76, 80, 82, 84],
  },
  {
    id: "lai",
    name: "Leaf Area Index (LAI) Canopy Radiative Transfer",
    source: "Sentinel-2 Biophysical Processor",
    family: "biomass",
    status: "calibration-required",
    resolution: "10 m",
    revisit: "5 days",
    description: "One-sided green leaf area per unit ground surface area estimated through PROSAIL model inversion.",
    agronomicUse: "Provides physical biomass scaling factor to check against reported grain yield (harvest index).",
    currentValue: "3.42 m²/m²",
    baselineValue: "3.10 m²/m²",
    anomaly: "+10.3%",
    anomalyPositive: true,
    unit: "Canopy Area Ratio",
    sparklineData: [0.8, 1.2, 1.7, 2.3, 2.8, 3.1, 3.3, 3.38, 3.40, 3.42],
  },
  {
    id: "sentinel1_soil_moisture",
    name: "Sentinel-1 Radar Soil-Moisture Proxy",
    source: "Sentinel-1 SAR C-band",
    family: "soil",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "6–12 days",
    description: "Dielectric constant sensitivity in upper 0–5 cm topsoil calibrated against soil roughness.",
    agronomicUse: "Monitors seedbed moisture readiness before planting decisions in early November/December.",
    currentValue: "24.6% vol",
    baselineValue: "21.5% vol",
    anomaly: "+3.1% vol",
    anomalyPositive: true,
    unit: "Topsoil Moisture (0-5cm)",
    sparklineData: [16.2, 18.5, 21.0, 23.4, 26.1, 25.4, 24.8, 24.5, 24.7, 24.6],
  },
  {
    id: "sentinel2_soil_moisture",
    name: "Sentinel-2 Optical/SWIR Soil Drought Index",
    source: "Sentinel-2 MSI",
    family: "soil",
    status: "calibration-required",
    resolution: "20 m",
    revisit: "5 days",
    description: "Shortwave infrared soil absorption variations over bare and sparsely vegetated ground.",
    agronomicUse: "Pinpoints localized soil dryness before crops reach permanent wilting point.",
    currentValue: "0.29 (Hydrated)",
    baselineValue: "0.34",
    anomaly: "-14.7%",
    anomalyPositive: true,
    unit: "SWIR Drought Index",
    sparklineData: [0.46, 0.44, 0.41, 0.38, 0.35, 0.33, 0.31, 0.30, 0.29, 0.29],
  },
  {
    id: "landsat_soil_moisture",
    name: "Landsat Thermal Infrared Soil Water Proxy",
    source: "Landsat 8/9 TIRS",
    family: "soil",
    status: "calibration-required",
    resolution: "30 m (resampled)",
    revisit: "8–16 days",
    description: "Apparent Thermal Inertia (ATI) and Land Surface Temperature (LST) mapping ground water deficit.",
    agronomicUse: "Long-term soil moisture depletion trends across irrigation command areas.",
    currentValue: "28.5 °C (LST)",
    baselineValue: "30.8 °C",
    anomaly: "-2.3 °C",
    anomalyPositive: true,
    unit: "Surface Temperature",
    sparklineData: [32.4, 31.8, 31.0, 30.5, 29.8, 29.4, 29.0, 28.8, 28.6, 28.5],
  },
];
